services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/var/www/html
    networks:
      - app_network
    working_dir: /var/www/html
networks:
  app_network:
    name: app_network
