name: Go Backend

on:
  push:
    paths:
      - 'go-provider-backend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'go-provider-backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.2
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker Compose Installation
        run: docker-compose --version

      - name: Set up Docker Compose
        working-directory: go-provider-backend
        run: make build && make up && docker compose logs

      - name: Database migrations
        working-directory: go-provider-backend
        run: make migrate

      - name: Run tests
        working-directory: go-provider-backend
        run: make test

      - name: Get commit hash
        id: get_commit
        run: echo "::set-output name=commit_hash::$(git rev-parse HEAD)"

      - name: Run contract tests
        working-directory: go-provider-backend
        run: make test-contract
        env:
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
          PROVIDER_VERSION: ${{ steps.get_commit.outputs.commit_hash }}

  can_i_deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Can I deploy
        uses: pactflow/actions/can-i-deploy@v2
        with:
          to_environment: "production"
          application_name: "Backend"
          broker_url: ${{ secrets.PACT_BROKER_URL }}
          token: ${{ secrets.PACT_BROKER_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: can_i_deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Record deployment
        uses: pactflow/actions/record-deployment@v2
        with:
          environment: "production"
          application_name: "Backend"
          broker_url: ${{ secrets.PACT_BROKER_URL }}
          token: ${{ secrets.PACT_BROKER_TOKEN }}

      - name: Stop Docker Compose services
        if: always()
        working-directory: go-provider-backend
        run: docker-compose down
