name: PHP Backend

on:
  push:
    paths:
      - 'php-consumer-backend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'php-consumer-backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.2
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker Compose Installation
        run: docker-compose --version

      - name: Set up Docker Compose
        working-directory: php-consumer-backend
        run: make up

      - name: Composer install
        working-directory: php-consumer-backend
        run: make composer-install

      - name: Run Pact contract tests
        working-directory: php-consumer-backend
        run: make test-contract

      - name: Publish Pact files
        uses: pactflow/actions/publish-pact-files@v2
        with:
          pactfiles: php-consumer-backend/pacts/*.json
          broker_url: ${{ secrets.PACT_BROKER_URL }}
          token: ${{ secrets.PACT_BROKER_TOKEN }}

      - name: Stop Docker Compose services
        if: always()
        working-directory: php-consumer-backend
        run: docker-compose down
